// Code generated by ent, DO NOT EDIT.

package ent

import (
	"plassstic.tech/gopkg/plassstic-mgr/lib/ent/schema"
	"plassstic.tech/gopkg/plassstic-mgr/lib/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescBot is the schema descriptor for bot field.
	userDescBot := userFields[1].Descriptor()
	// user.DefaultBot holds the default value on creation for the bot field.
	user.DefaultBot = userDescBot.Default.(schema.Bot)
	// userDescEditable is the schema descriptor for editable field.
	userDescEditable := userFields[2].Descriptor()
	// user.DefaultEditable holds the default value on creation for the editable field.
	user.DefaultEditable = userDescEditable.Default.(schema.Editable)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.IDValidator is a validator for the "id" field. It is called by the builders before save.
	user.IDValidator = userDescID.Validators[0].(func(int) error)
}
